spring:
  datasource:
    initialization-mode:always
    platform:postgres
    url:jdbc:postgresql://localhost:5432/maryamdb
    username:alimov
    password:alik3669
    initialize:always
  batch:
    initialize-schema:always
  jpa:
    hibernate:
      ddl-auto:update
  #spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
  #spring.jackson.serialization.fail-on-empty-beans=false
  servlet:
    multipart:
      max-file-size:10MB
      max-request-size:10MB