

spring:
	datasource:
		url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
		username: ${PROD_DB_USERNAME}
		password: ${PROD_DB_PASSWORD}
		name: spring-blog
	    initialize:always
	jpa:
		properties:
			javax:
				persistence:
					create-database-schemas : true

		hibernate:
			ddl-auto:update:
	batch:
		initialize-schema:always


	sql:
		init:
			mode: always
