

spring:
	datasource:
		platform: postgres
		url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
		username: ${PROD_DB_USERNAME}
		password: ${PROD_DB_PASSWORD}
		name: spring-blog
		initialization-mode: always
		initialize: always
	resources:
		static-locations: file:uploads/
	jpa:
		properties:
			javax:
				persistence:
					create-database-schemas : true

		hibernate:
			ddl-auto:update:
	batch:
		initialize-schema:always


sql:
	init:
		mode: always
servlet:
	multipart:
		max-file-size: 10MB
		max-request-size: 10MB